on:
  push:
    tags:
      - '*'

jobs:
  build_test_deploy:
    name: Build & Test & Deploy
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'

      - name: Install dependencies
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

#      - name: Install firebase tools
#        run: npm install -g firebase-tools
#
#      - name: Prepare git branches for nx affected command
#        run: |
#          echo "Base branch: ${BASE_BRANCH}, current branch: ${HEAD_REF}"
#          git fetch origin ${BASE_BRANCH}
#          git fetch origin ${HEAD_REF}
#          git checkout ${BASE_BRANCH}
#          git checkout ${HEAD_REF}
#        env:
#          BASE_BRANCH: ${{github.base_ref}}
#          HEAD_REF: ${{github.head_ref}}

      #      - name: Format Check
      #        run: npx nx format:check --base=${BASE_BRANCH}
      #        env:
      #          BASE_BRANCH: ${{github.base_ref}}
      #
      #      - name: Lint
      #        run: npx nx affected:lint --base=${BASE_BRANCH}
      #        env:
      #          BASE_BRANCH: ${{github.base_ref}}

#      - name: Test
#        run: npx nx affected --target=test --base=${BASE_BRANCH}
#        env:
#          BASE_BRANCH: ${{github.base_ref}}
#
#      - name: Build
#        run: npx nx affected --target=build --base=${BASE_BRANCH}
#        env:
#          BASE_BRANCH: ${{github.base_ref}}

      - name: Deploy
        run: echo "$REF"
#        run: npx nx affected --target=deploy --base=${BASE_BRANCH}
        env:
          REF: ${{github.ref}}

